name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure Report
        run: npx allure-commandline generate allure-results --clean -o allure-report

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Allure Report
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Slack Notification
        if: always()
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data "{
            \"text\":\"✅ Playwright Test Execution Completed 🚀\n📊 Allure Report: https://ok-sushil.github.io/Playwright_Project001/\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: test

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4